<a href="https://apssdc.in"><img src="https://camo.githubusercontent.com/e7501c5948d48f88dad8ab2ab6bd448e1cfd6c79/68747470733a2f2f64726976652e676f6f676c652e636f6d2f75633f6578706f72743d646f776e6c6f61642669643d3135414b51365f2d42697857344b366d4c36525070684635454b58715946327a6a" width="800" align="center"></a>

<h1><center>Python Overview & Data Manipulation with NumPy</center></h1>

In [1]:
print("Hello World")

Hello World


### [Literate Programming](http://www.literateprogramming.com/knuthweb.pdf)

1. **Programming Environment**
    - Jupyter Notebook Environment
    - Markdown format for documentation
        - Headings
        - Lists
- **Python Overview**
    - input/output
    - Conditional Statements in python
        - if
        - if else
        - if-elif-else
    - List
    - Tuple
    - Dictionary
    - Files
    - Modules & Packages
- **Data Manipulation with NumPy**
    - Introduction
    - NumPy Arrays
    - NumPy Basics
    - Math
    - Random
    - Indexing

# Markdown Syntax

## Shortcuts in Jupyter Notebook

- **ShiftEnter** - Execute the cell
- *EscM* - code cell to matkdown cell
- ***EscY*** - markdown cell to code cell
- **EscA** - insert the cell above the current cell
- **EscB** - Insert the cell below the current cell
- **EscDD** - Deleting
- **EscL** - Inserting Line Numbers for the Currret Cell

# Python Overview

## Heading2

### Heading3
###### Heading6

<h1>Heading1</h1>

- Line1
- line2
    - Sub Point2
        - Sub Sub Point
    - Sub point2
    
    
1. Line1
2. Line2
    1. Line 2-1
    2. Line 2-2

In [4]:
name = input("Enter Your Name")

Enter Your Name123


In [5]:
print(name)

123


In [6]:
print(type(name))

<class 'str'>


In [7]:
name = int(input("Enter Your Name"))

Enter Your Name123


In [8]:
print(type(name))

<class 'int'>


## Conditional Statements

- if

### Syntax

```python
if condition:
    print("Hello World")
```
- if-else

### Syntax

```python
if condition:
    print("Hello World")
    print("Hello World Again")
else:
    print("Failed Condition")
```
- if-elif-else

### Syntax

```python
if condition:
    print("Hello World")
    print("Hello World Again")
elif condition:
    print("Hello World Agani and Again")
    print("Final Hello World Again")
else:
    print("Failed Condition")
```

In [9]:
if True:
    print("Hello World")

Hello World


- int, float, complex, boolean, string
- List, tuple, Disctionary, Set

In [10]:
s1 = 's1'
s2 = "S2"
s3 = '''s3
s4
s5'''
s4 = """s6
s7
s8"""

In [11]:
bol1, bol2, bol3 = True, False, None

com = 3+5j
a = 5
b = 5.5

### List

Which is stored Group of dissimilar data type of elements
- We can modify, update, remove existing elements in the list

In [12]:
li = [113, 5+6j, 52.5, 'APSSDC', True, None, ["Hey I'm a List"]]

print(li)
print(type(li))

[113, (5+6j), 52.5, 'APSSDC', True, None, ["Hey I'm a List"]]
<class 'list'>


In [13]:
li[0] = 115
print(li)

[115, (5+6j), 52.5, 'APSSDC', True, None, ["Hey I'm a List"]]


## Tuple - ()

Which is stored Group of dissimilar data type of elements
- We can't modify, update, remove existing elements in the tuple

In [14]:
tup1 = (113, 5+6j, 52.5, 'APSSDC', True, None, ["Hey I'm a List"], ("Haha I'm a Tuple"))

print(tup1)

(113, (5+6j), 52.5, 'APSSDC', True, None, ["Hey I'm a List"], "Haha I'm a Tuple")


In [15]:
tup1[0] = 115

TypeError: 'tuple' object does not support item assignment

### Dictionary

They are used to store data in `key:value` pairs
```Python
{"Key":"Value"}
```

In [16]:
dic1 = {'APSSDC':"Online Training"}

print(dic1)

{'APSSDC': 'Online Training'}


### Files

In [20]:
f = open('textFile.txt', mode = 'r')
line = f.readline()
print(line)
print('***********')
data = f.read()
print(data)

print(type(data), type(line))
f.close()

APSSDC

***********
Online
Data
Analysis
Using
Python
Traning
Program
<class 'str'> <class 'str'>


In [21]:
f = open('textFile.txt', mode = 'r')
lines = f.readlines()
print(lines)


print(type(lines))
f.close()

['APSSDC\n', 'Online\n', 'Data\n', 'Analysis\n', 'Using\n', 'Python\n', 'Traning\n', 'Program']
<class 'list'>


### Modules & Packages


- Module is a single python file created for specific task
- Packages is a bunch of module avalaible on a single folder with specific task

In [22]:
import arthematic

moduleName.FuntionName

In [23]:
arthematic.addition(5, 10)

15

In [24]:
arthematic.pi

3.14

In [26]:
import arthematic as ar

ar.addition(50, 1100)

1150

In [29]:
from arthematic import addition

addition(50, 500)

550

In [30]:
from arthematic import addition as add

add(50000, 500)

50500

```python
import packageName.module as alais
from package import module
from package.module import method/class/attribute
from package.module import method/class/attribute as alais
```

 **Data Manipulation with NumPy**
    - Introduction
    - NumPy Arrays
    - NumPy Basics
    - Math
    - Random
    - Indexing

### [Numpy Official Website](https://numpy.org/)

In [31]:
import numpy as np

```python

error:moduleNotFoundError
    
pip install PackageName
```

### Numpy Array

It is used to store similar group of DataType of elements


### Creating of Arrays



In [32]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array((1, 2, 3, 4, 5, 6))

arr1

array([1, 2, 3, 4, 5, 6])

In [33]:
type(arr1), type(arr2)

(numpy.ndarray, numpy.ndarray)

In [35]:
arr1.dtype, arr2.dtype

(dtype('int32'), dtype('int32'))

In [38]:
arr3 = np.array([1, 2, 3, 4, 5, 6], dtype = 'int8')
type(arr3), arr3.dtype

(numpy.ndarray, dtype('int8'))

In [39]:
arr4 = np.array([1, 2, 3, 5.5, 6.6, 9.9, 8.8])

arr4, type(arr4), arr4.dtype

(array([1. , 2. , 3. , 5.5, 6.6, 9.9, 8.8]), numpy.ndarray, dtype('float64'))

- strings , complex, float, int --> Strings
- complex, float, int --> Complex
- float, int --> float
- int -> int

In [40]:
arr5 = np.array([1, 2, 3, 5.5, 6.6, 9.9, 8.8, 4 + 5j])

arr5, type(arr5), arr5.dtype

(array([1. +0.j, 2. +0.j, 3. +0.j, 5.5+0.j, 6.6+0.j, 9.9+0.j, 8.8+0.j,
        4. +5.j]),
 numpy.ndarray,
 dtype('complex128'))

In [41]:
arr6 = np.array([1, 2, 3, 5.5, 6.6, 9.9, 8.8, 4 + 5j, 'APSSDC'])

arr6, type(arr6), arr6.dtype

(array(['1', '2', '3', '5.5', '6.6', '9.9', '8.8', '(4+5j)', 'APSSDC'],
       dtype='<U64'),
 numpy.ndarray,
 dtype('<U64'))

- a = 0
- b = 0.0
- c = ' '
- li =  []
- t1 = ()

In [42]:
zeros = np.zeros(50)

zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
zeros.shape

(50,)

In [44]:
d2 = np.array([[1, 5], [5, 6]])

d2.shape

(2, 2)

In [46]:
zeros = np.zeros((5, 2))

zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [49]:
one = np.ones((5, 5), dtype = int)
one

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [56]:
one_complex = np.ones((500, 500), dtype = 'complex64')
one_complex

array([[1.+0.j, 1.+0.j, 1.+0.j, ..., 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, ..., 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, ..., 1.+0.j, 1.+0.j, 1.+0.j],
       ...,
       [1.+0.j, 1.+0.j, 1.+0.j, ..., 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, ..., 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, ..., 1.+0.j, 1.+0.j, 1.+0.j]],
      dtype=complex64)

In [57]:
one_complex.shape

(500, 500)

In [60]:
one = np.ones((5, 15), dtype = int)
one

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [61]:
one.shape

(5, 15)

In [67]:
d3 = one.reshape(5, 5, 3)

In [64]:
d3.shape

(5, 5, 3)

In [65]:
d3

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [68]:
one.size

75

In [69]:
one.nbytes

300

In [70]:
one.dtype

dtype('int32')

In [73]:
(32 * 75) // 8

300